import type { NextPage } from "next";
import Head from "next/head";
import React, { useRef } from "react";
import HorizontalScrollExample from "../components/HorizontalScrolExample";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hack SVIT 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-smoky-black h-screen grid items-center scroll-smooth snap-x snap-mandatory">
        <HorizontalScrollExample/>
      </main>
    </div>
  );
};

export default Home;
